### ISSUE TITLE
Missing flow diagram

### ISSUE THREAD

**Issue by wpdebruin** [coldbox-modules/cbsecurity#2]
https://github.com/coldbox-modules/cbox-security/wiki/How-it-Works is missing a flow diagram which was present in the original wiki.
Without this diagram it is very hard to understand how cbsecurity works.
The firewall part is clear (at least to me, but I am using this for many years  now)
But what might be difficult to understand and is not so "firewall like"
- if an event or URL is WHITELISTED,  on a whitelist match the rule is more or less ignored and you continue to the following rule. 
- if an event is MATCHED in securylist, this is the LAST rule which will be evaluated, no matter if you are in a role or not (cfsecurity) or no matter if your custom validator returns true or false.  If false you will be redirected and all other rules will be ingnored. This is absolutely important for the order of rules (so mor specific rules first). The analogy with firewalls also fails a bit here, because in firewall most of the time you have a BLOCK or ALLOW rule. Here a rule can be both, depending on the outcome of your validator.

If you still have the original flow diagram somewhere it would be very helpful, at least it made me understand the cbsecurity. If the diagram is there I will volunteer for writing a bit more elaborated example so this stuff is easier to understand.

**Comment by lmajano** [comment]
I'll make sure we add them to the new book

**Comment by wpdebruin** [comment]
Yes, this is the one which was in the old docs.
Makes you better understand how cbsecurity works.
Might need some extra explanation in text and examples to show the real power. It is really a pity people are not using this more often, because most scenario’s can be covered with this plugin.
As said, if you need help.. or I could write some blog post about how people can use cbsecurity.
If you port it to gitbook I could do some pull requests 😊

And a big thank you for all the work you and the team are doing on coldbox, commandbox and all the other box stuff. It really inspires me, wished I had more time and more projects to do in coldbox.
We still have some customer who could really benefit from coldbox, but until now I can’t convince them….

Wil

Van: Luis Majano [mailto:notifications@github.com]
Verzonden: woensdag 14 maart 2018 17:05
Aan: coldbox-modules/cbox-security <cbox-security@noreply.github.com>
CC: Wil de Bruin | Site4U <wdb@site4u.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [coldbox-modules/cbox-security] Missing flow diagram (#2)


I'll make sure we add them to the new book
