### ISSUE TITLE
CBSecurity Visualizer - Invalid Data Type when creating cbsecurity_logs table on Oracle

### ISSUE THREAD

**Issue by shreddtech** [coldbox-modules/cbsecurity#46]
## What are the steps to reproduce this issue?

1. When using Oracle db
2. Enable visualizer in cbsecurity
3. Set "autoCreate" to true in /config/cbsecurity.cfc > Firewall > logs

## What happens?

Error when creating securityRule column - Invalid DataType ( LongText )

## What were you expecting to happen?

For Oracle, using ( CLOB ) works in place of LongText

## Any logs, error output, etc?

…

## Any other comments?

…

## What versions are you using?
CBSecurity 3.4.1, ColdBox 7, Oracle 12c
**Operating System:** …
Ubuntu 22 LTS
**Package Version:** …

**Comment by lmajano** [comment]
Ok, I have updated it to match `clob` on Oracle.  Can you please try now

**Comment by lmajano** [comment]
However, try on the `cbsecurity@be` once it passes the build: https://github.com/coldbox-modules/cbsecurity/actions/runs/6184037673
