### ISSUE TITLE
Cbsecurity generate "refresh_token"

### ISSUE THREAD

**Issue by LucidSonal** [coldbox-modules/cbsecurity#50]
## What are the steps to reproduce this issue?
1. I am using Cbsecurity and cbauth modules.
2. I added Jwt settings in "/config/Coldbox.cfc" (moduleSettings).
3. I am expecting to generate "refresh_token" On hitting url.
4. But it is not doing the same as per the documentation (https://coldbox-security.ortusbooks.com/jwt/refresh-tokens). 
5. **Settings used:** 
cbsecurity : {
    // The WireBox ID of the authentication service to use in cbSecurity which must adhere to the cbsecurity.interfaces.IAuthService interface.
    authenticationService  : "authenticationService@cbauth",
    // WireBox ID of the user service to use
    userService             : "",
    // The name of the variable to use to store an authenticated user in prc scope if using a validator that supports it.
    prcUserVariable         : "oCurrentUser",
    // JWT Settings
    jwt                     : {
        // The issuer authority for the tokens, placed in the `iss` claim
        issuer                          : "",
        // The jwt secret encoding key, defaults to getSystemEnv( "JWT_SECRET", "" )
        // This key is only effective within the `config/Coldbox.cfc`. Specifying within a module does nothing.
        secretKey               : getSystemSetting( "JWT_SECRET", "" ),
        // by default it uses the authorization bearer header, but you can also pass a custom one as well.
        customAuthHeader        : "x-auth-token",
        // The expiration in minutes for the jwt tokens
        expiration              : 60, 
        // If true, enables refresh tokens, token creation methods will return a struct instead
        // of just the access token. e.g. { access_token: "", refresh_token : "" }
        enableRefreshTokens        : false,
        // The default expiration for refresh tokens, defaults to 30 days
        refreshExpiration          : 10080,
        // The Custom header to inspect for refresh tokens
        customRefreshHeader        : "x-refresh-token",
        // If enabled, the JWT validator will inspect the request for refresh tokens and expired access tokens
        // It will then automatically refresh them for you and return them back as
        // response headers in the same request according to the customRefreshHeader and customAuthHeader
        enableAutoRefreshValidator : false,
        // Enable the POST > /cbsecurity/refreshtoken API endpoint
        enableRefreshEndpoint      : true,
        // encryption algorithm to use, valid algorithms are: HS256, HS384, and HS512
        algorithm               : "HS512",
        // Which claims neds to be present on the jwt token or `TokenInvalidException` upon verification and decoding
        requiredClaims          : [] ,
        // The token storage settings
        tokenStorage            : {
            // enable or not, default is true
            "enabled"       : true
            // A cache key prefix to use when storing the tokens
            "keyPrefix"     : "cbjwt_", 
            // The driver to use: db, cachebox or a WireBox ID
            "driver"        : "cachebox",
            // Driver specific properties
            "properties"    : {
                cacheName : "default"
            }
        }
    }
}

6. Enable this setting **( enableRefreshTokens   : false,)** to true.

## What happens?

Not updating module config variables.

## What were you expecting to happen?
....
## Any logs, error output, etc?

Not Found!
![image](https://github.com/coldbox-modules/cbsecurity/assets/155729337/9dbd5c52-f5d2-4375-a206-88c0dacd2d85)

## Any other comments?
....

## What versions are you using?

**Operating System:** Windows 
**Package Version:** 11

**Comment by lmajano** [comment]
I believe you are not enabling the refresh tokens. Did you reinit the application.  If you do so,m then you would get the refresh token when you login.
