### ISSUE TITLE
Event Caching Causes Duplicate Headers

### ISSUE THREAD

**Issue by homestar9** [coldbox-modules/cbsecurity#51]
## What are the steps to reproduce this issue?

1. Create a new ColdBox App and install cbsecurity.
3. Use the configuration defaults if you like.
4. Ensure `eventCaching` is `true` in your Coldbox.cfc config file.
5. Enable inline event caching on the Main.cfc handler's Index() method:
```
function index( event, rc, prc ) cache="true" cacheTimeout="60" {
 ...
}
```
6. Start the server and load the web root /
7. Note the response headers:
![image](https://github.com/coldbox-modules/cbsecurity/assets/5341142/9dd1505b-e092-4690-89d3-e991bffa16f6)

9. Refresh the browser to bring up the cached event
10. Note all of the response headers added by cbsecurity are duplicated:

![image](https://github.com/coldbox-modules/cbsecurity/assets/5341142/3cdce3f2-7a29-4eb7-a76b-9eb96f818526)

## What happens?

Response headers are duplicated. This occurs on both Lucee and ACF engines.

## Any other comments?

Perhaps `setHTTPHeader()` in RequestContext could have an additional boolean argument called `overwrite`.  If set to true, it would check the existing header array and overwrite if it finds a match.

```
function setHTTPHeader( 
     statusCode, 
     statusText = "", 
     name, 
     value = "", 
     boolean overwrite=true
 ){
 ```
 The `overwrite` argument must also be passed to `addHeader()` on the response object so the array can be checked first.

The downside of the above approach is the additional processing time required for checking the array every time you want to add a header.  Therefore, it may not be the most performant way to solve the problem.

Here's a reference to the specs on HTTP headers.  
https://datatracker.ietf.org/doc/html/rfc7230#section-3.2.2

Based on my interpretation, header names should not be duplicated, except for special cases like `Set-Cookie`.   Browsers will interpret duplicate header key names as a comma-separated list, like this:

```
Strict-Transport-Security: max-age: 31536000;
Strict-Transport-Security: max-age: 31536000;
```
The above will be interpreted as:
```
Strict-Transport-Security: max-age: 31536000, max-age: 31536000;
```
Depending on the header, it could cause unintended issues.

## What versions are you using?

**Operating System:**  Windows Server + Commandbox
**Package Version:** 3.4.2+4

**Comment by lmajano** [comment]
Verified and resolved in ColdBox
[COLDBOX-1269](https://ortussolutions.atlassian.net/browse/COLDBOX-1269)
Do not add double headers if `event.setHTTPHeader()` is called more than once

Please test `coldbox@be` so we can patch it.

**Comment by homestar9** [comment]
@lmajano, I attempted to test on `coldbox@be`, but [COLDBOX-1269](https://ortussolutions.atlassian.net/browse/COLDBOX-1269) isn't present in the current `be` version.

**Comment by lmajano** [comment]
You can try now
