### ISSUE TITLE
JWT Validator - where is it??

### ISSUE THREAD

**Issue by tgmweb** [coldbox-modules/cbsecurity#9]
The docs state for JWT I should use the JWTValidator, however, it doesn't seem to exist?

[https://coldbox-security.ortusbooks.com/jwt/jwt-validator](url)

`cbsecurity.models.JwtValidator`

`cbsecurity = {
    validator = "JwtValidator@cbsecurity"
}`

Yet there is no JwTValidator in cbsecurity.models?

**Comment by lmajano** [comment]
Thanks! Updated the docs
